<!-- Template Scripts -->
<script src="{{ asset('assets/js/template/State.min.js') }}"></script>
<script src="{{ asset('assets/js/template/Component.min.js') }}"></script>
<script src="{{ asset('assets/js/template/Plugin.min.js') }}"></script>
<script src="{{ asset('assets/js/template/Base.min.js') }}"></script>
<script src="{{ asset('assets/js/template/Config.min.js') }}"></script>
<script src="{{ asset('assets/js/template/Menubar.min.js') }}"></script>
<script src="{{ asset('assets/js/template/Gridmenu.min.js') }}"></script>
<script src="{{ asset('assets/js/template/Sidebar.min.js') }}"></script>
<script src="{{ asset('assets/js/template/PageAside.min.js') }}"></script>
<script src="{{ asset('assets/js/template/menu.min.js') }}"></script>